// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ButtonOne: typeof import('./src/components/Global/ButtonOne.vue')['default']
    ButtonTwo: typeof import('./src/components/Global/ButtonTwo.vue')['default']
    ElButton: typeof import('element-ui/lib/button')['default']
    ElDivider: typeof import('element-ui/lib/divider')['default']
    ElMenu: typeof import('element-ui/lib/menu')['default']
    ElMenuItem: typeof import('element-ui/lib/menu-item')['default']
    ElTag: typeof import('element-ui/lib/tag')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
  }
}

export {}
